name: create_release

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build lib and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: v1kko/daetools-libs
          file: dockerfiles/daetools_libs.docker

  build_py38:
    runs-on: ubuntu-20.04
    needs: build

    steps:
        
      - name: Build py38
        run: |
          docker build -f dockerfiles/daetools_python_bindings.docker \
          --build-arg PY_VERSION=3.8 -t daetools_py38 .

      - name: Extract Artifacts
        run: |
          rm -rf daetools
          mkdir -p daetools
          docker run -v `pwd`/daetools-package:/out daetools_py38 rsync -a
          /daetools/trunk/daetools-package/  /out/

  build_py39:
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - name: Build py38
        run: |
          docker build -f dockerfiles/daetools_python_bindings.docker \
          --build-arg PY_VERSION=3.9 -t daetools_py39 .

      - name: Extract Artifacts
        run: |
          rm -rf daetools
          mkdir -p daetools
          docker run -v `pwd`/daetools-package:/out daetools_py39 rsync -a
          /daetools/trunk/daetools-package/  /out/
  publish_artifact:
    runs-on: ubuntu-20.04
    needs: [build_py39, build_py38]
    steps:
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: daetools-package
          name: daetools-package
