name: create_release

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build
        run: |
          docker build -f ./dockerfiles/daetools_py38.docker -t daetools_py38 ./
      - name: Extract Artifacts
        run: |
          rm -rf daetools
          mkdir -p daetools
          docker run -v `pwd`/daetools:/out daetools_py38 cp -r /daetools/trunk/daetools-package  /out
      - name: Package Artifacts
        run: |
          tar -czf daetools_py38.tar.gz daetools
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: daetools_py38.tar.gz
          name: daetools_py38.tar.gz
