name: create_ubuntu_amd64_release

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build lib and push
        run: |
          docker build -f ./dockerfiles/daetools-libs.docker -t daetools-libs .
          #docker push ghcr.io/v1kko/daetools-libs

      - name: Build py38
        run: |
          docker build -f ./dockerfiles/daetools_python_bindings.docker \
          --build-arg PY_VERSION=3.8 -t daetools_py38 .

      - name: Extract Artifacts
        run: |
          docker run -v `pwd`/daetools-package:/out daetools_py38 rsync -a \
          /daetools/trunk/daetools-package/  /out/

      - name: Build py39
        run: |
          docker build -f ./dockerfiles/daetools_python_bindings.docker \
          --build-arg PY_VERSION=3.9 -t daetools_py39 .

      - name: Extract Artifacts
        run: |
          docker run -v `pwd`/daetools-package:/out daetools_py39 rsync -a \
          /daetools/trunk/daetools-package/  /out/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: daetools-package
          name: daetools-package
